/**
 * Énumérations pour le module de dépenses
 */

// Catégories de dépenses
const EXPENSE_CATEGORY = {
  OFFICE_SUPPLIES: 'OFFICE_SUPPLIES',
  TRAVEL: 'TRAVEL',
  MEALS: 'MEALS',
  ACCOMMODATION: 'ACCOMMODATION',
  SOFTWARE: 'SOFTWARE',
  HARDWARE: 'HARDWARE',
  SERVICES: 'SERVICES',
  MARKETING: 'MARKETING',
  TAXES: 'TAXES',
  RENT: 'RENT',
  UTILITIES: 'UTILITIES',
  SALARIES: 'SALARIES',
  INSURANCE: 'INSURANCE',
  MAINTENANCE: 'MAINTENANCE',
  TRAINING: 'TRAINING',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  OTHER: 'OTHER'
};

// Statuts de dépenses
const EXPENSE_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PAID: 'PAID'
};

// Méthodes de paiement pour les dépenses
const EXPENSE_PAYMENT_METHOD = {
  CREDIT_CARD: 'CREDIT_CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CASH: 'CASH',
  CHECK: 'CHECK',
  PAYPAL: 'PAYPAL',
  OTHER: 'OTHER'
};

module.exports = {
  EXPENSE_CATEGORY,
  EXPENSE_STATUS,
  EXPENSE_PAYMENT_METHOD
};
